### ISSUE TITLE
No module named 'mapanalyzerext'

### ISSUE THREAD

**Issue by tdog123** [AresSC2/ares-sc2-bot-template#3]
Hi - Looks like a great library for bot development. I tried installing using the instructions at "https://github.com/AresSC2/ares-sc2-bot-template" and I get an error: **ModuleNotFoundError: No module named 'mapanalyzerext'.** More specifically, it's being called here: **Lib\site-packages\map_analyzercext\wrapper.py", line 8, in <module> from mapanalyzerext import (...**

I'm on Windows and I can confirm that my vanilla python-sc2 bot loads correctly. It looks like maybe the MapAnalyzer package isn't loading correctly. I read up some on the MapAnalyzer package and there may to be platform-dependent binary, but I'm not sure if I'm going down the right path.

Has this confirmed to be building successfully on Windows machines?

Thanks!

**Comment by tdog123** [comment]
I figured it out. 

I did need the Windows extension binary. The docs [here](https://github.com/spudde123/SC2MapAnalysis) say: **Check the most recent BuildCExtension Github Action workflow. Then scroll to the bottom to download the artifact for your OS**" But the artifacts expired there. You can get them here instead: https://github.com/spudde123/SC2MapAnalysis/releases. It's successfully loading now on my machine.

**Comment by raspersc2** [comment]
Hi @tdog123, just got round to this issue.
Apologies for the frustration! Will try to fix this for future users

**Comment by tdog123** [comment]
@raspersc2 No worries. I'm not very knowledgeable in github workflows. :-/ Got it up and running now though! The Docs are especially helpful! Thanks!
